# Generated by Django 3.1.5 on 2021-01-20 03:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfistapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMpProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=4, default=Decimal('0.00000'), max_digits=6)),
            ],
        ),
    ]
